"""empty message

Revision ID: 438672edda08
Revises: 45bee7eb4560
Create Date: 2018-03-27 23:23:12.581318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438672edda08'
down_revision = '45bee7eb4560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('users', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'users', ['users'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'users')
    # ### end Alembic commands ###
